print("hello world")
print(1 + 1)
print("Odejmowanie, operator -")
print("4-1 =", 4 - 1)
print("Dodawanie, operator +")
print("4 + 12 = ", 4 + 12)
print("Dzielenie całkowite, operator //")
print("11 // 5 = ", 11 // 5)
print("Dzielenie modulo, operator %")
print("5 % 2 = ", 5 % 2)
print("Potęgowanie, operator **. 3*3 =", 3**3)
print("Pierwiastek, brak standardowego operatora - można przez ** 0.5 np. 9 ** 0.5 = ", 9 ** 0.5)
print("Liczba zespolona to na przykład ", 1+2j+2+3j)

